name: Node CI environment

on:
  # Workflow is triggered when a PR targeting main branch is opened, reopened, or synchronized
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 'main'
    # Workflow is not triggered if the following files are only changed in the PR
    paths-ignore: [ 'README.md', '.gitignore' ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm login
        run:
          npm config set //registry.npmjs.org/:_authToken=$NPM_READONLY_AUTH_TOKEN
        env:
          NPM_READONLY_AUTH_TOKEN: ${{ secrets.NPM_READONLY_AUTH_TOKEN }}

      - name: npm install
        working-directory: ./application
        run: npm i --ignore-scripts

      - name: Run ESLint
        uses: ninosaurus/eslint-check@v5
        with:
          eslint-config-path: "./application/assets/js/.eslintrc.json"
          custom-directory: "./application"
